USE cursofrontendtarde;
CREATE TABLE CLIENTES(
	DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(20),
    DIRECCION VARCHAR(40),
    PRIMARY KEY (DNI)
);

CREATE TABLE BANCOS(
	ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(20),
    CIUDAD VARCHAR(20),
    PRIMARY KEY (ID)
);

CREATE TABLE CUENTAS(
	ID INT NOT NULL AUTO_INCREMENT,
    DNI VARCHAR(9) NOT NULL,
    IDBANCO INT NOT NULL,
    SALDO DECIMAL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DNI) REFERENCES CLIENTES (DNI),
    FOREIGN KEY (IDBANCO) REFERENCES BANCOS (ID)
    );
    